### ISSUE TITLE
The version (1.2.0) of Uno was not updated in Uno.cpp

### ISSUE THREAD

**Issue by amontoison** [cvanaret/Uno#65]
https://github.com/cvanaret/Uno/blob/37e22cb21a147cb36429f889ea617cd38b3922a7/uno/Uno.cpp#L120

**Comment by odow** [comment]
I have checklists in our documentation, because it's soooooo easy to overlook things when making a new release:

https://github.com/jump-dev/JuMP.jl/blob/master/docs/src/developers/checklists.md#making-a-release

Highly, highly recommend. I haven't messed up a release (touch wood) since I introduced them.

Usage looks like: https://github.com/jump-dev/JuMP.jl/pull/3854

**Comment by cvanaret** [comment]
@amontoison well spotted! That was fixed in 60c18fc.
@odow thank you, that's a great idea!
